### ISSUE TITLE
Idea: Add feed.xml so others can subscribe

### ISSUE THREAD

**Issue by vsoch** [chrispahm/chrispahm.github.com#1]
It would be great to render a feed.xml from the root so that folks can subscribe with (still widely used, never will die!) rss!  [Here is an example](https://github.com/vsoch/vsoch.github.io/blob/master/feed.xml) of one rendered with jekyll, and primarily you just need to loop through posts and render sections, so I think you could use the same strategy as your home page (even the same limit for the top 15 posts).

**Comment by vsoch** [comment]
If you are able to add simple documentation in the README for how to build, I could also try giving it a shot - I'm not terribly skilled with node, but hey, isn't working on little things a good way to get practice? :)

**Comment by chrispahm** [comment]
Hey there!
thanks for the feedback 😊I just fiddled around with the [feed](https://www.npmjs.com/package/feed) package and it was really straightforward! There's now a [feed.xml](https://chrispahm.github.io/feed.xml) in the root (also an [atom.xml](https://chrispahm.github.io/atom.xml and [json.json](https://chrispahm.github.io/json.json)). The readme now contains a section about how to build the blog and start the live-server as well!
Let me know what you think!

**Comment by vsoch** [comment]
It worked perfectly! I was able to add you to feedly now, because the feed was discovered. Closing issue, and looking forward to your future posts!

**Comment by vsoch** [comment]
One more cool share (that I just found this evening!) If you have a custom build process you are running locally to push, you could use GitHub actions ([example](https://www.innoq.com/en/blog/github-actions-automation/)) to run on merge to master, and for some source directory, to build and then deploy the content to gh-pages or directly to master. If you don't have a build process, then disregard everything that I just said!
